force-app/main/default/objects/TicTocEvent__e/TicTocEvent__e.object-meta.xml
<CustomObject>
    <label>TicTocEvent</label>
    <pluralLabel>TicTocEvents</pluralLabel>
</CustomObject>

force-app/main/default/objects/TicTocEvent__e/fields/action__c.field-meta.xml
<CustomField>
    <fullName>action__c</fullName>
    <label>action</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TicTocEvent__e/fields/corditnate__c.field-meta.xml
<CustomField>
    <fullName>corditnate__c</fullName>
    <label>corditnate</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TicTocEvent__e/fields/Game_Id__c.field-meta.xml
<CustomField>
    <fullName>Game_Id__c</fullName>
    <label>Game_Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TicTocEvent__e/fields/PlayerName__c.field-meta.xml
<CustomField>
    <fullName>PlayerName__c</fullName>
    <label>PlayerName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TicTocEvent__e/fields/SenderGameId__c.field-meta.xml
<CustomField>
    <fullName>SenderGameId__c</fullName>
    <label>SenderGameId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PublishTicTacToeGameEvent.cls
public class PublishTicTacToeGameEvent {
    
    
    
    
    
    @AuraEnabled
    public static void joinGame(String receiverGameId,String playerName){
        List<TicTocEvent__e> TicTacToeEventList = new List<TicTocEvent__e>();
        TicTacToeEventList.add(new TicTocEvent__e(PlayerName__c = playerName,game_id__c = receiverGameId,action__c = 'join game'));
        
        List<Database.SaveResult> results = EventBus.publish(TicTacToeEventList);
        
        printDebugLogs(results);
    }
    
    @AuraEnabled
    public static void sendJoinConfirmation(String receiverGameId,string senderGameId,String playerName){
        List<TicTocEvent__e> TicTacToeEventList = new List<TicTocEvent__e>();
        TicTacToeEventList.add(new TicTocEvent__e(PlayerName__c = playerName,game_id__c = receiverGameId,SenderGameId__c = senderGameId,action__c = 'join confirmation'));
        
        List<Database.SaveResult> results = EventBus.publish(TicTacToeEventList);
        
        printDebugLogs(results);
    }
    
    @AuraEnabled
    public static void playMove(String cordinate,String senderId){
        List<TicTocEvent__e> TicTacToeEventList = new List<TicTocEvent__e>();
        TicTacToeEventList.add(new TicTocEvent__e(corditnate__c = cordinate,game_id__c = senderId,action__c = 'receiver move'));
        
        List<Database.SaveResult> results = EventBus.publish(TicTacToeEventList);
        
        printDebugLogs(results);
    }
    
    public static void printDebugLogs(List<Database.SaveResult> results){
        for (Database.SaveResult sr : results) {
            if (sr.isSuccess()) {
                System.debug('Successfully published event.');
            } else {
                for(Database.Error err : sr.getErrors()) {
                    System.debug('Error returned: ' +
                                err.getStatusCode() +
                                ' - ' +
                                err.getMessage());
                }
            }       
        }
    }

}